name: Lighthouse

on:
  push:
    branches: [master]
  pull_request:

concurrency:
  cancel-in-progress: true
  group: lighthouse-${{ github.head_ref }}

jobs:

  lighthouseci:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set yarn cache up
      uses: c-hive/gha-yarn-cache@v2

    - name: Install dependencies
      run: yarn --frozen-lockfile --prefer-offline

    - name: Build application
      run: yarn build
      env:
        POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        NEXT_PUBLIC_MAPBOX_TOKEN: ${{ secrets.NEXT_PUBLIC_MAPBOX_TOKEN }}

    - name: Install lighthouse
      run: yarn global add @lhci/cli@0.6.x

    - name: Run lighthouse
      run: lhci autorun
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
