name: Tests

on:
  pull_request:

concurrency:
  cancel-in-progress: true
  group: tests-${{ github.head_ref }}

jobs:

  test:
    name: Test application
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set yarn cache up
      uses: c-hive/gha-yarn-cache@v2

    - name: Install dependencies
      run: yarn --frozen-lockfile --prefer-offline

    - name: Run tests
      run: yarn test --coverage

    - name: Publish code coverage
      uses: codecov/codecov-action@v2
      with:
        flags: snapshots
        fail_ci_if_error: true
